### ISSUE TITLE
Running a fresh ./rigger checkout errors out

### ISSUE THREAD

**Issue by nathansamson** [deis/rigger#12]
```
[nathan@zeta rigger]$ ./rigger checkout
/home/nathan/Documenten/rigger/../rigger/lib/functions.sh: line 93: /home/nathan/.rigger/vars: No such file or directory
ERROR: *** command failed: deis:checkout. ***
[nathan@zeta rigger]$ 
```

Using latest master f5a69ec0d91c12b2641e1a0db74ea71c90c1c53c

**Comment by nathansamson** [comment]
Apparantly I have to run configure first, but a better error handling would still be peferred

**Comment by sgoings** [comment]
Ah yes. You'll need to do a `./rigger configure` first. If you're interested, you could definitely take a crack at improving the error output on this command. Also be aware that I have some better work in the provider-rewrite branch that I'll be queueing up to merge into master this afternoon...
