### ISSUE TITLE
Refine rigger -> deis provider interface

### ISSUE THREAD

**Issue by sgoings** [deis/rigger#15]
In https://github.com/deis/deis/pull/4315 there was a discussion that instead of having [config, install, create, check, destroy].sh files, we should just have [config, install, create, check, destroy] files (no .sh suffix).

This would enable us to write those scripts in any language.

To support this, we'd need to have certain rigger library functions on the path:
- save-var (updates/saves variables into the rigger vars file)
- logging functions (for common logging output/ui)
- functions related to prompting/reading suggested answers, etc.

**Comment by bacongobbler** [comment]
+1. Heroku used this convention as well (`detect`, `build`, `release`) which allowed them to write their buildpacks in any language. Their Ruby buildpack is actually scripted in Ruby.

**Comment by helgi** [comment]
Also how JuJu does it
