### ISSUE TITLE
Proposal: use containerized backend

### ISSUE THREAD

**Issue by krancour** [deis/rigger#35]
Depending on which underlying provisioner is used, rigger has a number of underlying dependencies that can include python, pip, ruby, rubygems, the aws cli, terraform, etc.  This long and variable list of dependencies could be pared down to _just_ a dependency on Docker (a very reasonable and low barrier to entry) by evolving rigger into an ultra-lightweight binary client that actually gets work done by handing it off to a containerized "back end" that is a more sophisticated binary in a standardized provisioning environment that's pre-loaded with all the necessary dependencies.

**Comment by rimusz** [comment]
:+1:

**Comment by krancour** [comment]
This issue is pretty old.  I actually fooled around with this during an internal hackathon back in mid-October and it's plausible, but much more complex than it appears at first glance.  Combine that with what is, at least, a reduced need for rigger going forward with Deis v2 and it seems the best thing to do with this issue is close it.
