### ISSUE TITLE
Following blog post example doesn't work - xip.io doesn't know of deis.XXX.XXX.XXX.XXX.xip.io

### ISSUE THREAD

**Issue by n1rvana** [deis/rigger#60]
I'm following the blog post here:
https://deis.com/blog/2016/ramping-up-rigger-deploying-deis-digitalocean

🌀  deis auth:register http://deis.${DEIS_TEST_DOMAIN}
http://deis.MY.IPV4.ADD.RESS.xip.io does not appear to be a valid Deis controller.
Make sure that the Controller URI is correct and the server is running.
Error: Get http://deis.MY.IPV4.ADD.RESS.xip.io/v1/: dial tcp: lookup deis.MY.IPV4.ADD.RESS.xip.io on MY.DNS.PROVIDER.IP:53: no such host

The reason for this is pretty obvious- xip.io provides resolution for IPaddres.xip.io not deis.ipaddress.xip.io

Only deviation from the instructions is I used the latest version of DEIS: v1.12.2

Is there a easy way to use rigger to make a DO cluster like this, but specify DNS (say using DO's built in DNS Service?)

I post this in case you want to change the blog post or there's an actual bug.  Close if it's not helpful for you. :-)

**Comment by bacongobbler** [comment]
> The reason for this is pretty obvious- xip.io provides resolution for IPaddres.xip.io not deis.ipaddress.xip.io

We've been using xip.io for development purposes. xip is a wildcard reverse DNS resolver that provides resolution for any IP address. As per [their website](http://xip.io/):

> xip.io is a magic domain name that provides wildcard DNS
> for any IP address. Say your LAN IP address is 10.0.0.1.
> Using xip.io,
> 
> ```
> 10.0.0.1.xip.io   resolves to   10.0.0.1
> www.10.0.0.1.xip.io   resolves to   10.0.0.1
> mysite.10.0.0.1.xip.io   resolves to   10.0.0.1
> foo.bar.10.0.0.1.xip.io   resolves to   10.0.0.1
> ```

So I'm not sure why DNS wouldn't resolve for you. Perhaps your DNS server does not allow xip.io domain names?

For what it's worth, I'm using Google's DNS servers (8.8.8.8 or 8.8.4.4) without issues. I've been using both Vagrant (172.17.8.100.xip.io) as well as DO for development purposes (MY.PUBLIC.DIGITALOCEAN.IPADDRESS.xip.io).

**Comment by sgoings** [comment]
Hey @n1rvana! I think it'd be totally awesome to use DO's own DNS service. Looks like Terraform even supports it pretty nicely: https://www.terraform.io/docs/providers/do/r/domain.html

I'll take a crack at providing that behavior in Rigger.

**Comment by n1rvana** [comment]
@bacongobbler The reason is that xip.io doesn't know of a subdomain named "deis" -- it takes the IP from the domain requested and returns that IP as the address record.  Rigger is adding "dies." to the front.

@sgoings That would be cool! Love terraform.

**Comment by krancour** [comment]
@n1rvana, @bacongobbler is just quoting xip.io's own documentation [here](http://xip.io/).

If you have any doubt that it works, try the following:

```
$ dig deis.1.2.3.4.xip.io
```

And see a result like this:

```
...
;; ANSWER SECTION:
deis.1.2.3.4.xip.io.    300 IN  A   1.2.3.4
...
```

Is it possible that the root cause of your issue is something else?

**Comment by n1rvana** [comment]
@krancour Whoops my goof. Alas I destroyed that cluster so I can't be sure what went wrong. I would guess that given my error above, that somehow the application that should answer at dies.whatever didn't get started up.  I'm going to do another deployment today and will report back if I get the same problem.
