### ISSUE TITLE
Consider a more flexible "current environment" decision logic

### ISSUE THREAD

**Issue by sgoings** [deis/rigger#8]
Right now we hold a link in `~/.rigger/vars` to the vars file of the most recent `rigger configure`'d vars file.

This makes it a pain to deal with multiple cluster `provision` `test` etc. operations in parallel (such as in release testing).

Some options that have been discussed:
- keep this logic but also allow people to pass in a name for their cluster at configuration time as well as for all the commands

```
./rigger provision aws-1
./rigger test aws-2
```
- make the link smarter to just look in a directory structure within ~/.rigger/... that corresponds to the user's current working directory

**Comment by krancour** [comment]
> make the link smarter to just look in a directory structure within ~/.rigger/... that corresponds to the user's current working directory

^ too much "magic," imo

I love the first option though.
